package kdw007;

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import org.openqa.selenium.*;

public class Scenario2Case1 extends kdw007Common {

    @BeforeEach
    public void setUp() throws Exception {
        screenshotPath = "images/kdw007/Scenario2Case1";
        this.init();
    }

    @Test
    public void test() throws Exception {
        //login申請者
        login("000001", "0");
        driver.get(domain + "nts.uk.at.web/view/kmk/012/a/index.xhtml");
        WaitPageLoad();
        driver.findElement(By.xpath("//tr[@data-id='1']")).click();
        driver.findElement(By.id("inpMonth")).clear();
        driver.findElement(By.id("inpMonth")).sendKeys("2019/07");
        driver.findElement(By.xpath("//body")).click();
        driver.findElement(By.id("btn_save")).click();
        closeMsg();
        // KDW003A 勤務報告書
        driver.get(domain + "nts.uk.at.web/view/kdw/003/a/index.xhtml");
        WaitPageLoad();
        closeDialog();
        driver.findElement(By.id("ccg001-btn-search-drawer")).click();
        WaitPageLoad();
        driver.findElement(By.id("ccg001-btn-search-all")).click();
        WaitPageLoad();
        closeDialog();
        // Case 1
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `023463`).id)");
        inputDate("2019/08/01", "2019/08/31");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("102");
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("出勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("900");
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("退勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("1600");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U161", "2019/08/21");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // reset data
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("001");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        closeMsg();
        closeDialog();
        Thread.sleep(2000);
        // case 2.1
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `018794`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("出勤時刻1", "08/19(月)").click();
        selectItemKdw003_1("出勤時刻1", "08/19(月)").click();
        selectItemKdw003_1("出勤時刻1", "08/19(月)").findElement(By.xpath("./div/input")).sendKeys("901");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U162", "2019/08/19");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(1000);
        // reset data
        selectItemKdw003_1("出勤時刻1", "08/19(月)").click();
        selectItemKdw003_1("出勤時刻1", "08/19(月)").click();
        selectItemKdw003_1("出勤時刻1", "08/19(月)").findElement(By.xpath("./div/input")).sendKeys("900");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        closeMsg();
        closeDialog();
        Thread.sleep(2000);
        // Case 2.2
        selectItemKdw003_1("勤務種類", "08/20(火)").click();
        selectItemKdw003_1("勤務種類", "08/20(火)").click();
        selectItemKdw003_1("勤務種類", "08/20(火)").findElement(By.xpath("./div/input")).sendKeys("001");
        selectItemKdw003_1("退勤時刻1", "08/20(火)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/20(火)").click();
        selectItemKdw003_1("退勤時刻1", "08/20(火)").findElement(By.xpath("./div/input")).sendKeys("1559");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U162", "2019/08/20");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 3
        selectItemKdw003_1("勤務種類", "08/20(火)").click();
        selectItemKdw003_1("勤務種類", "08/20(火)").click();
        selectItemKdw003_1("勤務種類", "08/20(火)").findElement(By.xpath("./div/input")).sendKeys("102");
        selectItemKdw003_1("退勤時刻1", "08/20(火)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/20(火)").click();
        selectItemKdw003_1("退勤時刻1", "08/20(火)").findElement(By.xpath("./div/input")).sendKeys("1500");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U163", "2019/08/20");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 4
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `019246`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/24(土)").click();
        selectItemKdw003_1("勤務種類", "08/24(土)").click();
        selectItemKdw003_1("勤務種類", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("007");
        selectItemKdw003_1("就業時間帯", "08/24(土)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/24(土)").click();
        selectItemKdw003_1("就業時間帯", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("A10");
        selectItemKdw003_1("出勤時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("出勤時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("900");
        selectItemKdw003_1("退勤時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("退勤時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("1630");
        selectItemKdw003_1("休憩開始時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻1", "08/24(土)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("1200");
        selectItemKdw003_1("休憩終了時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻1", "08/24(土)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("1300");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U164", "2019/08/24");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 5
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `023463`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/22(木)").click();
        selectItemKdw003_1("勤務種類", "08/22(木)").click();
        selectItemKdw003_1("勤務種類", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("002");
        closeMsg();
        selectItemKdw003_1("出勤時刻1", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/22(木)").click();
        selectItemKdw003_1("出勤時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1300");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U165", "2019/08/22");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // reset data
        selectItemKdw003_1("勤務種類", "08/22(木)").click();
        selectItemKdw003_1("勤務種類", "08/22(木)").click();
        selectItemKdw003_1("勤務種類", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("001");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        closeMsg();
        closeDialog();
        Thread.sleep(2000);
        // Case 6
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `001291`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("予定勤務種類", "08/22(木)").click();
        selectItemKdw003_1("予定勤務種類", "08/22(木)").click();
        selectItemKdw003_1("予定勤務種類", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("106");
        selectItemKdw003_1("勤務種類", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("勤務種類", "08/22(木)").click();
        selectItemKdw003_1("勤務種類", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("001");
        selectItemKdw003_1("就業時間帯", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/22(木)").click();
        selectItemKdw003_1("就業時間帯", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("081");
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1259");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U172", "2019/08/22");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // reset data
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1300");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        closeMsg();
        closeDialog();
        Thread.sleep(2000);
        // Case 7
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `018794`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("021");
        selectItemKdw003_1("就業時間帯", "08/21(水)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/21(水)").click();
        selectItemKdw003_1("就業時間帯", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("A11");
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("退勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("1200");
        selectItemKdw003_1("遅刻時間1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("遅刻時間1", "08/21(水)").click();
        selectItemKdw003_1("遅刻時間1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("001");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U173", "2019/08/21");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // reset data
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("001");
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("退勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("1600");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        closeMsg();
        closeDialog();
        Thread.sleep(2000);
        // Case 8
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `019019`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("出勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("出勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("出勤時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("900");
        selectItemKdw003_1("退勤時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("退勤時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("1730");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U175", "2019/08/24");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // reset data
        selectItemKdw003_1("出勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("出勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("出勤時刻1", "08/24(土)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("退勤時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("退勤時刻1", "08/24(土)").findElement(By.xpath("./div/input")).clear();
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        closeMsg();
        closeDialog();
        Thread.sleep(2000);
        // Case 9
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `018234`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/24(土)").click();
        selectItemKdw003_1("勤務種類", "08/24(土)").click();
        selectItemKdw003_1("勤務種類", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("002");
        selectItemKdw003_1("就業時間帯", "08/24(土)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/24(土)").click();
        selectItemKdw003_1("就業時間帯", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("010");
        selectItemKdw003_1("退勤時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("退勤時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("1400");
        selectItemKdw003_1("遅刻時間1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("遅刻時間1", "08/24(土)").click();
        selectItemKdw003_1("遅刻時間1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("001");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U178", "2019/08/24");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 11
        selectItemKdw003_1("勤務種類", "08/24(土)").click();
        selectItemKdw003_1("勤務種類", "08/24(土)").click();
        selectItemKdw003_1("勤務種類", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("002");
        selectItemKdw003_1("就業時間帯", "08/24(土)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/24(土)").click();
        selectItemKdw003_1("就業時間帯", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("010");
        selectItemKdw003_1("出勤時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("出勤時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("1300");
        selectItemKdw003_1("退勤時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("退勤時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("1730");
        selectItemKdw003_1("遅刻時間1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("遅刻時間1", "08/24(土)").click();
        selectItemKdw003_1("遅刻時間1", "08/24(土)").findElement(By.xpath("./div/input")).clear();
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U180", "2019/08/24");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
         // Case 12
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `003210`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("002");
        selectItemKdw003_1("就業時間帯", "08/21(水)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/21(水)").click();
        selectItemKdw003_1("就業時間帯", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("051");
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("出勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("1300");
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("退勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("1730");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U181", "2019/08/21");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // reset data
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("001");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        closeMsg();
        closeDialog();
        Thread.sleep(2000);
        // Case 15
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `019246`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("出勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("931");
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("退勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("1629");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U184", "2019/08/21");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 16
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `009621`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/27(火)").click();
        selectItemKdw003_1("勤務種類", "08/27(火)").click();
        selectItemKdw003_1("勤務種類", "08/27(火)").findElement(By.xpath("./div/input")).sendKeys("002");
        selectItemKdw003_1("就業時間帯", "08/27(火)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/27(火)").click();
        selectItemKdw003_1("就業時間帯", "08/27(火)").findElement(By.xpath("./div/input")).sendKeys("041");
        selectItemKdw003_1("出勤時刻1", "08/27(火)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/27(火)").click();
        selectItemKdw003_1("出勤時刻1", "08/27(火)").findElement(By.xpath("./div/input")).sendKeys("1300");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U185", "2019/08/27");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // reset data
        selectItemKdw003_1("勤務種類", "08/27(火)").click();
        selectItemKdw003_1("勤務種類", "08/27(火)").click();
        selectItemKdw003_1("勤務種類", "08/27(火)").findElement(By.xpath("./div/input")).sendKeys("001");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        closeMsg();
        closeDialog();
        Thread.sleep(2000);
        // Case 19
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `019246`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/24(土)").click();
        selectItemKdw003_1("勤務種類", "08/24(土)").click();
        selectItemKdw003_1("勤務種類", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("002");
        selectItemKdw003_1("就業時間帯", "08/24(土)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/24(土)").click();
        selectItemKdw003_1("就業時間帯", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("A10");
        selectItemKdw003_1("出勤時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("出勤時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("1300");
        selectItemKdw003_1("退勤時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("退勤時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("1630");
        selectItemKdw003_1("休憩開始時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻1", "08/24(土)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("1200");
        selectItemKdw003_1("休憩終了時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻1", "08/24(土)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("1300");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U188", "2019/08/24");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 20
        selectItemKdw003_1("勤務種類", "08/24(土)").click();
        selectItemKdw003_1("勤務種類", "08/24(土)").click();
        selectItemKdw003_1("勤務種類", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("007");
        selectItemKdw003_1("就業時間帯", "08/24(土)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/24(土)").click();
        selectItemKdw003_1("就業時間帯", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("A10");
        selectItemKdw003_1("出勤時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("出勤時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("930");
        selectItemKdw003_1("退勤時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("退勤時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("1200");
        selectItemKdw003_1("休憩開始時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻1", "08/24(土)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("1200");
        selectItemKdw003_1("休憩終了時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻1", "08/24(土)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("1300");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U189", "2019/08/24");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // reset data
        selectItemKdw003_1("勤務種類", "08/24(土)").click();
        selectItemKdw003_1("勤務種類", "08/24(土)").click();
        selectItemKdw003_1("勤務種類", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("090");
        selectItemKdw003_1("退勤時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("退勤時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("1630");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        closeMsg();
        closeDialog();
        Thread.sleep(2000);
        // Case 21
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("008");
        selectItemKdw003_1("就業時間帯", "08/21(水)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/21(水)").click();
        selectItemKdw003_1("就業時間帯", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("A10");
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("出勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("930");
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("退勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).clear();
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U192", "2019/08/21");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 22
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `001291`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("予定勤務種類", "08/22(木)").click();
        selectItemKdw003_1("予定勤務種類", "08/22(木)").click();
        selectItemKdw003_1("予定勤務種類", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("106");
        selectItemKdw003_1("勤務種類", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("勤務種類", "08/22(木)").click();
        selectItemKdw003_1("勤務種類", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("094");
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1259");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U193", "2019/08/22");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        //  Case 23
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `019019`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("100");
        selectItemKdw003_1("就業時間帯", "08/21(水)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/21(水)").click();
        selectItemKdw003_1("就業時間帯", "08/21(水)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("出勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("900");
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("退勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("1730");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U194", "2019/08/21");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 24
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("101");
        selectItemKdw003_1("就業時間帯", "08/21(水)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/21(水)").click();
        selectItemKdw003_1("就業時間帯", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("100");
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("出勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("退勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("休憩開始時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻1", "08/21(水)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("1200");
        selectItemKdw003_1("休憩終了時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻1", "08/21(水)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("1300");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U195", "2019/08/21");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 25
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `001917`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("出勤時刻1", "08/22(木)").click();
        selectItemKdw003_1("出勤時刻1", "08/22(木)").click();
        selectItemKdw003_1("出勤時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("900");
        selectItemKdw003_1("退勤時刻1", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/22(木)").click();
        selectItemKdw003_1("退勤時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1730");
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1200");
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1300");
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1715");
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1745");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U196", "2019/08/22");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 26
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1700");
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1800");
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").findElement(By.xpath("./div/input")).clear();
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U197", "2019/08/22");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 27
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `018794`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/27(火)").click();
        selectItemKdw003_1("勤務種類", "08/27(火)").click();
        selectItemKdw003_1("勤務種類", "08/27(火)").findElement(By.xpath("./div/input")).sendKeys("002");
        selectItemKdw003_1("就業時間帯", "08/27(火)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/27(火)").click();
        selectItemKdw003_1("就業時間帯", "08/27(火)").findElement(By.xpath("./div/input")).sendKeys("A11");
        selectItemKdw003_1("出勤時刻1", "08/27(火)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/27(火)").click();
        selectItemKdw003_1("出勤時刻1", "08/27(火)").findElement(By.xpath("./div/input")).sendKeys("1300");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U198", "2019/08/27");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // reset data
        selectItemKdw003_1("勤務種類", "08/27(火)").click();
        selectItemKdw003_1("勤務種類", "08/27(火)").click();
        selectItemKdw003_1("勤務種類", "08/27(火)").findElement(By.xpath("./div/input")).sendKeys("001");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        closeMsg();
        closeDialog();
        Thread.sleep(2000);
        // Case 28
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `001917`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1200");
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1300");
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1715");
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1730");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U199", "2019/08/22");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 29
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1700");
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1730");
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").findElement(By.xpath("./div/input")).clear();
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U200", "2019/08/22");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 30
        selectItemKdw003_1("出勤時刻1", "08/22(木)").click();
        selectItemKdw003_1("出勤時刻1", "08/22(木)").click();
        selectItemKdw003_1("出勤時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("459");
        selectItemKdw003_1("実働時間", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("実働時間", "08/22(木)").click();
        selectItemKdw003_1("実働時間", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("730");
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1200");
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1300");
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").findElement(By.xpath("./div/input")).clear();
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U201", "2019/08/22");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 31
        selectItemKdw003_1("出勤時刻1", "08/22(木)").click();
        selectItemKdw003_1("出勤時刻1", "08/22(木)").click();
        selectItemKdw003_1("出勤時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("900");
        selectItemKdw003_1("退勤時刻1", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/22(木)").click();
        selectItemKdw003_1("退勤時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("2901");
        selectItemKdw003_1("実働時間", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("実働時間", "08/22(木)").click();
        selectItemKdw003_1("実働時間", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("730");
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1200");
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1300");
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").findElement(By.xpath("./div/input")).clear();
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U202", "2019/08/22");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 32
        selectItemKdw003_1("勤務種類", "08/24(土)").click();
        selectItemKdw003_1("勤務種類", "08/24(土)").click();
        selectItemKdw003_1("勤務種類", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("090");
        selectItemKdw003_1("就業時間帯", "08/24(土)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/24(土)").click();
        selectItemKdw003_1("就業時間帯", "08/24(土)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("出勤時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("出勤時刻1", "08/24(土)").findElement(By.xpath("./div/input")).sendKeys("900");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U203", "2019/08/24");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // reset data
        selectItemKdw003_1("出勤時刻1", "08/24(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/24(土)").click();
        selectItemKdw003_1("出勤時刻1", "08/24(土)").findElement(By.xpath("./div/input")).clear();
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        closeMsg();
        closeDialog();
        Thread.sleep(2000);
        // Case 33
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `019019`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("101");
        selectItemKdw003_1("就業時間帯", "08/21(水)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/21(水)").click();
        selectItemKdw003_1("就業時間帯", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("100");
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("出勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("900");
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("退勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("1730");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U204", "2019/08/21");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 35
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `019246`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("011");
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("出勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("930");
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("退勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).clear();
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U206", "2019/08/21");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 36
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `019019`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").click();
        selectItemKdw003_1("勤務種類", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("001");
        selectItemKdw003_1("就業時間帯", "08/21(水)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/21(水)").click();
        selectItemKdw003_1("就業時間帯", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("100");
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("出勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/21(水)").click();
        selectItemKdw003_1("退勤時刻1", "08/21(水)").findElement(By.xpath("./div/input")).sendKeys("1730");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U301", "2019/08/21");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 37
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `001917`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("出勤時刻1", "08/22(木)").click();
        selectItemKdw003_1("出勤時刻1", "08/22(木)").click();
        selectItemKdw003_1("出勤時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("900");
        selectItemKdw003_1("退勤時刻1", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/22(木)").click();
        selectItemKdw003_1("退勤時刻1", "08/22(木)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("実働時間", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("実働時間", "08/22(木)").click();
        selectItemKdw003_1("実働時間", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("730");
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1200");
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1300");
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").findElement(By.xpath("./div/input")).clear();
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U302", "2019/08/22");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 38
        selectItemKdw003_1("出勤時刻1", "08/22(木)").click();
        selectItemKdw003_1("出勤時刻1", "08/22(木)").click();
        selectItemKdw003_1("出勤時刻1", "08/22(木)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("退勤時刻1", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/22(木)").click();
        selectItemKdw003_1("退勤時刻1", "08/22(木)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("実働時間", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("実働時間", "08/22(木)").click();
        selectItemKdw003_1("実働時間", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("730");
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1200");
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/22(木)").findElement(By.xpath("./div/input")).sendKeys("1300");
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").click();
        selectItemKdw003_1("休憩開始時刻2", "08/22(木)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").click();
        selectItemKdw003_1("休憩終了時刻2", "08/22(木)").findElement(By.xpath("./div/input")).clear();
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U303", "2019/08/22");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        this.uploadTestLink(904, 220);
    }

    @AfterEach
    public void tearDown() throws Exception {
        driver.quit();
        String verificationErrorString = verificationErrors.toString();
        if (!"".equals(verificationErrorString)) {
            fail(verificationErrorString);
        }
    }
}