package kdw007;

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import org.openqa.selenium.*;

public class Scenario1Case1 extends kdw007Common {

    @BeforeEach
    public void setUp() throws Exception {
        screenshotPath = "images/kdw007/Scenario1Case1";
        this.init();
    }

    @Test
    public void test() throws Exception {
        //login申請者
        login("000001", "0");
        driver.get(domain + "nts.uk.at.web/view/kmk/012/a/index.xhtml");
        WaitPageLoad();
        driver.findElement(By.xpath("//tr[@data-id='1']")).click();
        driver.findElement(By.id("inpMonth")).clear();
        driver.findElement(By.id("inpMonth")).sendKeys("2019/07");
        driver.findElement(By.xpath("//body")).click();
        driver.findElement(By.id("btn_save")).click();
        closeMsg();
        // KDW003A 勤務報告書
        driver.get(domain + "nts.uk.at.web/view/kdw/003/a/index.xhtml");
        WaitPageLoad();
        closeDialog();
        driver.findElement(By.id("ccg001-btn-search-drawer")).click();
        WaitPageLoad();
        driver.findElement(By.id("ccg001-btn-search-all")).click();
        WaitPageLoad();
        closeDialog();
        // Case 1
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `001256`).id)");
        inputDate("2019/08/01", "2019/08/31");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("102");
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("出勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("900");
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("退勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("1730");
        selectItemKdw003_1("実働時間", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("実働時間", "08/30(金)").click();
        selectItemKdw003_1("実働時間", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("731");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U101", "2019/08/30");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // case 2
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("001");
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("出勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("900");
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("退勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("1730");
        selectItemKdw003_1("実働時間", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("実働時間", "08/30(金)").click();
        selectItemKdw003_1("実働時間", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("000");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U102", "2019/08/30");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 3
        selectItemKdw003_1("勤務種類", "08/31(土)").click();
        selectItemKdw003_1("勤務種類", "08/31(土)").click();
        selectItemKdw003_1("勤務種類", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("006");
        selectItemKdw003_1("就業時間帯", "08/31(土)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/31(土)").click();
        selectItemKdw003_1("就業時間帯", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("081");
        selectItemKdw003_1("出勤時刻1", "08/31(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/31(土)").click();
        selectItemKdw003_1("出勤時刻1", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("900");
        selectItemKdw003_1("退勤時刻1", "08/31(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/31(土)").click();
        selectItemKdw003_1("退勤時刻1", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("1730");
        selectItemKdw003_1("実働時間", "08/31(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("実働時間", "08/31(土)").click();
        selectItemKdw003_1("実働時間", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("830");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U105", "2019/08/31");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 4
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `002235`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("出勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("1730");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U106", "2019/08/30");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(1000);
        // reset data
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("出勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("900");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        closeMsg();
        closeDialog();
        Thread.sleep(2000);
        // Case 5
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `001256`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("010");
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("出勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("900");
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("退勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("実働時間", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("実働時間", "08/30(金)").click();
        selectItemKdw003_1("実働時間", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("730");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U107", "2019/08/30");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 6
        selectItemKdw003_1("勤務種類", "08/31(土)").click();
        selectItemKdw003_1("勤務種類", "08/31(土)").click();
        selectItemKdw003_1("勤務種類", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("007");
        selectItemKdw003_1("就業時間帯", "08/31(土)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/31(土)").click();
        selectItemKdw003_1("就業時間帯", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("081");
        selectItemKdw003_1("出勤時刻1", "08/31(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/31(土)").click();
        selectItemKdw003_1("出勤時刻1", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("900");
        selectItemKdw003_1("退勤時刻1", "08/31(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/31(土)").click();
        selectItemKdw003_1("退勤時刻1", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("1245");
        selectItemKdw003_1("実働時間", "08/31(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("実働時間", "08/31(土)").click();
        selectItemKdw003_1("実働時間", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("345");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U110", "2019/08/31");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 7
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `003014`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("001");
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("出勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("901");
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("退勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("1730");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U111", "2019/08/30");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 8
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `001256`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("010");
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("出勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("900");
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("退勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("1730");
        selectItemKdw003_1("実働時間", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("実働時間", "08/30(金)").click();
        selectItemKdw003_1("実働時間", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("730");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U116", "2019/08/30");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 9
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `017004`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("102");
        selectItemKdw003_1("予定退勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("予定退勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("予定退勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("1630");
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("出勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("930");
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("退勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("1230");
        selectItemKdw003_1("休憩開始時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻1", "08/30(金)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/30(金)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("休憩終了時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻1", "08/30(金)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/30(金)").findElement(By.xpath("./div/input")).clear();
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U117", "2019/08/30");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 10
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `003014`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("102");
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("出勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("900");
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("退勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("1245");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U118", "2019/08/30");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 11
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `001256`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/31(土)").click();
        selectItemKdw003_1("勤務種類", "08/31(土)").click();
        selectItemKdw003_1("勤務種類", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("006");
        selectItemKdw003_1("就業時間帯", "08/31(土)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/31(土)").click();
        selectItemKdw003_1("就業時間帯", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("081");
        selectItemKdw003_1("出勤時刻1", "08/31(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/31(土)").click();
        selectItemKdw003_1("出勤時刻1", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("900");
        selectItemKdw003_1("退勤時刻1", "08/31(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/31(土)").click();
        selectItemKdw003_1("退勤時刻1", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("1244");
        selectItemKdw003_1("実働時間", "08/31(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("実働時間", "08/31(土)").click();
        selectItemKdw003_1("実働時間", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("344");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U126", "2019/08/31");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
         // Case 12
         js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `017004`).id)");
         driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
         WaitPageLoad();
         closeDialog();
         js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
         selectItemKdw003_1("勤務種類", "08/31(土)").click();
         selectItemKdw003_1("勤務種類", "08/31(土)").click();
         selectItemKdw003_1("勤務種類", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("006");
         selectItemKdw003_1("就業時間帯", "08/31(土)").click();
         closeMsg();
         Thread.sleep(1000);
         selectItemKdw003_1("就業時間帯", "08/31(土)").click();
         selectItemKdw003_1("就業時間帯", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("A10");
         selectItemKdw003_1("出勤時刻1", "08/31(土)").click();
         Thread.sleep(1000);
         selectItemKdw003_1("出勤時刻1", "08/31(土)").click();
         selectItemKdw003_1("出勤時刻1", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("930");
         selectItemKdw003_1("退勤時刻1", "08/31(土)").click();
         Thread.sleep(1000);
         selectItemKdw003_1("退勤時刻1", "08/31(土)").click();
         selectItemKdw003_1("退勤時刻1", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("1229");
         driver.findElement(By.xpath("//body")).click();
         WaitPageLoad();
         driver.findElement(By.xpath("//button[@class='proceed']")).click();
         WaitPageLoad();
         driver.findElement(By.xpath("//button[@class='large']")).click();
         WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
         switchFrame();
         scrollToPos("U127", "2019/08/31");
         screenShot();
         driver.findElement(By.id("dialogClose")).click();
         Thread.sleep(2000);
         // Case 13.1
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `001256`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("102");
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("出勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("退勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("実働時間", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("実働時間", "08/30(金)").click();
        selectItemKdw003_1("実働時間", "08/30(金)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("入門時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("入門時刻1", "08/30(金)").click();
        selectItemKdw003_1("入門時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("830");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U136", "2019/08/30");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 13.2
        selectItemKdw003_1("入門時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("入門時刻1", "08/30(金)").click();
        selectItemKdw003_1("入門時刻1", "08/30(金)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("退門時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退門時刻1", "08/30(金)").click();
        selectItemKdw003_1("退門時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("1800");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U136", "2019/08/30");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 14
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `017004`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("001");
        selectItemKdw003_1("予定退勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("予定退勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("予定退勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("1630");
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("出勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("930");
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("退勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("1630");
        selectItemKdw003_1("休憩開始時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻1", "08/30(金)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/30(金)").findElement(By.xpath("./div/input")).clear();
        selectItemKdw003_1("休憩終了時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻1", "08/30(金)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/30(金)").findElement(By.xpath("./div/input")).clear();
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U144", "2019/08/30");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 15
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").click();
        selectItemKdw003_1("勤務種類", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("001");
        selectItemKdw003_1("予定退勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("予定退勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("予定退勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("1630");
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("出勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("930");
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/30(金)").click();
        selectItemKdw003_1("退勤時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("1830");
        selectItemKdw003_1("休憩開始時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩開始時刻1", "08/30(金)").click();
        selectItemKdw003_1("休憩開始時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("1200");
        selectItemKdw003_1("休憩終了時刻1", "08/30(金)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("休憩終了時刻1", "08/30(金)").click();
        selectItemKdw003_1("休憩終了時刻1", "08/30(金)").findElement(By.xpath("./div/input")).sendKeys("1300");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U145", "2019/08/30");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 16
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `001256`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/31(土)").click();
        selectItemKdw003_1("勤務種類", "08/31(土)").click();
        selectItemKdw003_1("勤務種類", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("002");
        selectItemKdw003_1("出勤時刻1", "08/31(土)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/31(土)").click();
        selectItemKdw003_1("出勤時刻1", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("900");
        selectItemKdw003_1("退勤時刻1", "08/31(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/31(土)").click();
        selectItemKdw003_1("退勤時刻1", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("1730");
        selectItemKdw003_1("実働時間", "08/31(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("実働時間", "08/31(土)").click();
        selectItemKdw003_1("実働時間", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("730");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U157", "2019/08/31");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 17
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `017004`).id)");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/31(土)").click();
        selectItemKdw003_1("勤務種類", "08/31(土)").click();
        selectItemKdw003_1("勤務種類", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("002");
        selectItemKdw003_1("就業時間帯", "08/31(土)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/31(土)").click();
        selectItemKdw003_1("就業時間帯", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("A10");
        selectItemKdw003_1("出勤時刻1", "08/31(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("出勤時刻1", "08/31(土)").click();
        selectItemKdw003_1("出勤時刻1", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("930");
        selectItemKdw003_1("退勤時刻1", "08/31(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/31(土)").click();
        selectItemKdw003_1("退勤時刻1", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("1329");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U158", "2019/08/31");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        //  Case 18
        js.executeScript("__viewContext.vm.selectedEmployee(_.find(__viewContext.vm.lstEmployee(), o => o.code == `003014`).id)");
        inputDate("2019/08/01", "2019/08/31");
        driver.findElement(By.xpath("//button[@id='btnExtraction']")).click();
        WaitPageLoad();
        closeDialog();
        js.executeScript("$('.mgrid-free').scrollTop($('.mgrid-free')[1].scrollHeight)");
        selectItemKdw003_1("勤務種類", "08/31(土)").click();
        selectItemKdw003_1("勤務種類", "08/31(土)").click();
        selectItemKdw003_1("勤務種類", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("002");
        selectItemKdw003_1("就業時間帯", "08/31(土)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/31(土)").click();
        selectItemKdw003_1("就業時間帯", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("010");
        selectItemKdw003_1("退勤時刻1", "08/31(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/31(土)").click();
        selectItemKdw003_1("退勤時刻1", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("1344");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U159", "2019/08/31");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        // Case 19
        selectItemKdw003_1("勤務種類", "08/31(土)").click();
        selectItemKdw003_1("勤務種類", "08/31(土)").click();
        selectItemKdw003_1("勤務種類", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("002");
        selectItemKdw003_1("就業時間帯", "08/31(土)").click();
        closeMsg();
        Thread.sleep(1000);
        selectItemKdw003_1("就業時間帯", "08/31(土)").click();
        selectItemKdw003_1("就業時間帯", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("010");
        selectItemKdw003_1("退勤時刻1", "08/31(土)").click();
        Thread.sleep(1000);
        selectItemKdw003_1("退勤時刻1", "08/31(土)").click();
        selectItemKdw003_1("退勤時刻1", "08/31(土)").findElement(By.xpath("./div/input")).sendKeys("1730");
        driver.findElement(By.xpath("//body")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='proceed']")).click();
        WaitPageLoad();
        driver.findElement(By.xpath("//button[@class='large']")).click();
        WaitElementLoad(By.xpath("//iframe[contains(@name,'window')]"));
        switchFrame();
        scrollToPos("U160", "2019/08/31");
        screenShot();
        driver.findElement(By.id("dialogClose")).click();
        Thread.sleep(2000);
        this.uploadTestLink(902, 219);
    }

    @AfterEach
    public void tearDown() throws Exception {
        driver.quit();
        String verificationErrorString = verificationErrors.toString();
        if (!"".equals(verificationErrorString)) {
            fail(verificationErrorString);
        }
    }
}